import initTranslations from "@/app/i18n";
import { TranslationsProvider } from "@/helper/translationProvider";
import flat from "../../../projects/flat.json";

import styles from "./style.module.scss";

import { HeaderWhite } from "@/components/header/headerWhite";
import { Container } from "@/components/ui/container";

import { Footer } from "@/components/footer";
import { ContentWithSlider } from "@/components/contentWithSlider";

const i18nNamespaces = ["flatInteriorDesign"];

export const metadata = {
  title: "Flat Interior Design - Garcia Global",
  description: "Generated by create next app",
};

export default async function FlatInteriorDesign({ params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  const advantages = [
    "kitchen",
    "bathroom",
    "bedroom",
    "hallway",
    "diningArea",
  ];
  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
      <HeaderWhite />
      <main className={styles.flat}>
        <Container className={styles.flat__container}>
          <div className={styles.flat__titleContainer}>
            <h1>{t("title")}</h1>
          </div>
          <div className={styles.flat__content}>
            {advantages.map((item, index) => (
              <ContentWithSlider
                title={t(item)}
                text={t(item + "Descr")}
                key={index}
                imgs={flat[item]}
                textColor="black"
                arrowColor="black"
              />
            ))}
          </div>
        </Container>
      </main>
      <Footer locale={locale} />
    </TranslationsProvider>
  );
}
