import styles from "./style.module.scss";
import { Footer } from "../../../components/footer/index";
import { HeaderBlack } from "../../../components/header/headerBlack";
import initTranslations from "../../i18n";
import { TranslationsProvider } from "../../../helper/translationProvider/index"; 
import { Videos } from "../../../components/videos";
import { Container } from "../../../components/ui/container/index";
import Link from "next/link";
import { ArrowPrjct } from "../../../components/ui/icons/arrowPrjct";

const i18nNamespaces = ["houseInteriorDesign"];

export const metadata = {
  title: "House Interior Design - Garcia Global",
  description: "Generated by create next app",
};

export default async function HouseInteriorDesign({ params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
         <div className={styles.houseInteriorDesign__header}>  
     <HeaderBlack locale={locale} />
     </div>

      <main className={styles.houseInteriorDesign}>
        <section className={styles.topSection}>
          <Container className={styles.topSection__top}>
            <h1>{t("title")}</h1> 
          </Container>
          <div className={styles.topSection__bottom}>
            <p>{t("text")}</p>
            <Link href={"/interiorAll"}>
              <span>{t("viewFullGallery")}</span>
            </Link>
          </div>
        </section>
        <Videos locale={locale} />
        {/* <Map locale={locale} /> */}
      </main>
      <Footer locale={locale} />
    </TranslationsProvider>
  );
}
