import initTranslations from "../../i18n";
import { TranslationsProvider } from "../../../helper/translationProvider";

import styles from "./style.module.scss";

import { HeaderBlack } from "../../../components/header/headerBlack";
import { Container } from "../../../components/ui/container/index";
import { StepItem } from "../../../components/individualProjecting/stepItem/index";
import { Footer } from "../../../components/footer/index";

const i18nNamespaces = ["individualProjecting"];

export const metadata = {
  title: "Individual Projecting - Garcia Global",
  description: "Generated by create next app",
};

export default async function IndividualProjecting({ params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
     <div className={styles.individualProjecting__header}>  
     <HeaderBlack locale={locale} />
     </div>
      <main className={styles.individualProjecting}>
        <Container className={styles.individualProjecting__container}>
          <h1>{t("title")}</h1>
          <div className={styles.individualProjecting__content}>
            {Array.from({ length: 4 }).map((_, index) => (
              <StepItem
                key={index}
                title={`0${index + 1} ` + t(`itemTitle${index + 1}`)}
                text={t(`itemText${index + 1}`)}
              />
            ))}
          </div>
        </Container>
      </main>
      <Footer locale={locale} />
    </TranslationsProvider>
  );
}
