import { dir } from "i18next";
import i18nConfig from "../../../i18nConfig";
import { roboto } from "../../fonts/index";
import "./default.scss";

export const metadata = {
  title: "Garcia Global",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={roboto.className}
        style={{ display: "flex", flexDirection: "column" }}
      >
        {children}
      </body>
    </html>
  );
}
