import initTranslations from "@/app/i18n";
import { TranslationsProvider } from "@/helper/translationProvider";
import { ProjectItem } from "@/components/projectItem";
import { Container } from "@/components/ui/container";
import styles from "./style.module.scss";
import Link from "next/link";
import { ArrowPrjct } from "@/components/ui/icons/arrowPrjct";
import { BackToHome } from "@/components/backToHome";

const i18nNamespaces = ["home"];

export const metadata = {
  title: "Interior All - Garcia Global",
  description: "Generated by create next app",
};

export default async function InteriorAll({ params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}
    >
      <main className={styles.interiorDesing}>
        <Container className={styles.interiorAll__container}>
          <div className="">
            <BackToHome locale={locale} />
            <div className={styles.interiorDesing__titleContainer}>
              <div className={styles.interiorDesing__textTitleBox}>
                <h2>{t("interirDesignTitle")}</h2>
                <p>{t("interirDesignText")}</p>
              </div>
              <div className={styles.interiorDesing__projectsContainer}>
                <Link href={"#"}>
                  <div className={styles.interiorDesing__projectItem}>
                    <span>Mynysterkiy</span>
                    <ArrowPrjct color="white" width={20} height={20} />
                  </div>
                </Link>
                <div className="">
                  <Link href={"#"}>
                    <div className={styles.interiorDesing__projectItem}>
                      <span>Villa Cartagena</span>
                      <ArrowPrjct color="white" width={20} height={20} />
                    </div>
                  </Link>
                  <Link href={"#"}>
                    <div className={styles.interiorDesing__projectItem}>
                      <span>Townhouse Albacete</span>
                      <ArrowPrjct color="white" width={20} height={20} />
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          {Array.from({ length: 3 }).map((_, index) => (
            <section key={index}>
              <ProjectItem id={index + 1} locale={locale} />
            </section>
          ))}
        </Container>
        <div className={styles.interiorDesing__imgBg} />
      </main>
    </TranslationsProvider>
  );
}
